---
author: Pat
baseurl: /
description: "A brazen two-column <a href=\"http://jekyllrb.com\" target=\"_blank\">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href=\"https://twitter.com/mdo\" target=\"_blank\">@mdo</a>."
github:
  repo: "https://github.com/poole/hyde"
name: PJ
tagline: "A Jekyll theme"
title: Hyde
url: "https://twitter.com/mdo"
version: "2.1.0"
